### ISSUE TITLE
Why not close editor with Enter?

### ISSUE THREAD

**Issue by fracz** [sjurba/rebase-editor#1]
I always catch myself on "I have done everything -> Enter!" and then "Oh no, it's Q" :smiley:

**Comment by sjurba** [comment]
Right. And maybe Esc for abort..? I think I'll add those as default as well. But most importantly I'm working on adding support for custom keyboard bindings. #2

**Comment by fracz** [comment]
Exactly! Great job, BTW :+1:

**Comment by sjurba** [comment]
Enter and escape are now default keys to exit and abort.
