### ISSUE TITLE
Syntax coloring

### ISSUE THREAD

**Issue by dvdbng** [sjurba/rebase-editor#13]
When editing a interactive rebase with vim you get nice colors:
![](http://i.imgur.com/qenAE16.png)

In comparison, rebase-editor looks more plain
![](http://i.imgur.com/TESGyP7.png)

It would be nice if rebase-editor would highlight the command and the commit sha1 in a different color, to make the list more readable

**Comment by dvdbng** [comment]
Nevermind, didn't see the --color flag

**Comment by sjurba** [comment]
`git config --global sequence.editor "rebase-editor -c ^r,^c,^m"` looks like what you need..
