### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by michaelmior** [sjurba/rebase-editor#16]
Just a suggestion that syntax highlighting would be nice. vim normally does this for me and it's the one thing I'm missing after trying rebase-editor. I may try to hack together a PR myself with some simple colours.

**Comment by sjurba** [comment]
Did you see the --colors flag? It can even take a param to use custom colors..

**Comment by michaelmior** [comment]
Oh, I obviously missed that. Thanks for pointing out! Sorry for failing to RTFM :)

**Comment by michaelmior** [comment]
While nice, this doesn't really do quite the same thing. In vim, the action, commit ID, and message can all be displayed in different colours.

**Comment by sjurba** [comment]
Well thats how i implemented too.. The default colors are red, yellow and black. But you can choose your own colors, ex `-c ^r,^c,^y`

You can find more details in the readme. 😊

mvh
Sjur Bakka

**Comment by michaelmior** [comment]
I misread initially and deleted my comment, but you're too quick! Thanks :)
