### ISSUE TITLE
-c doesn't work when it's the last option

### ISSUE THREAD

**Issue by pmcelhaney** [sjurba/rebase-editor#18]
When -c is the last option and there are no colors specified, the argument parsing gets confused.

```sh
$ GIT_SEQUENCE_EDITOR="rebase-editor -c" git rebase -i master
No input file specified.
Could not execute editor
```

These cases work as expected.

```sh
$ GIT_SEQUENCE_EDITOR="rebase-editor -c -s" git rebase -i master
$ GIT_SEQUENCE_EDITOR="rebase-editor -c ^r,^y,^b" git rebase -i master
```

**Comment by pmcelhaney** [comment]
It was easy enough to work around that I didn't even bother looking into what the fix might be. I figured I would share in case anyone runs into the same problem.

**Comment by sjurba** [comment]
Super! Thanx. I think it should be quite simple to fix.

**Comment by sjurba** [comment]
So a better workaround for this is to end the command with `--`:
`GIT_SEQUENCE_EDITOR="rebase-editor -c --" git rebase -i master`

This is to usual way to signal that the rest of the line are not options. It is safe to use this with all or no options. I'll update the examples in the README to use it.

So I'm closing this as a won't fix.
