### ISSUE TITLE
Syntax Error in Node 6.13.0

### ISSUE THREAD

**Issue by austince** [sjurba/rebase-editor#26]
Running Node 6.13.0 on ubuntu 18.04, got the following error:
```
node_modules/rebase-editor/node_modules/string-kit/lib/format.js:624
                base = round( n / ( 1000 ** logDiv3 ) , roundStep[ logMod ] ) ;

SyntaxError: Unexpected token *
```

Since node 6 is officially supported, I think this is a bug.

**Comment by austince** [comment]
I have a PR in for string-kit https://github.com/cronvel/string-kit/pull/2

**Comment by sjurba** [comment]
I see that cronvel merged your PR and travis reports all builds are passing. Thanx!
