### ISSUE TITLE
Can't use rebase-editor with Intellij IDEA

### ISSUE THREAD

**Issue by Smolli** [sjurba/rebase-editor#28]
When using editor-config it's not possible to use the Reword or Interactive Rebase from IDEA any more. On the console there is following error:

```
git -c core.quotepath=false -c log.showSignature=false -c core.commentChar= rebase --interactive --rebase-merges --no-autosquash 2a1...987
Not a proper rebase file: 
label onto
reset onto
pick 8a4de21 <message>
pick 41d0918 <message>
 ...
error: There was a problem with the editor 'rebase-editor'.
```

Is there any chance this could be fixed?

**Comment by sjurba** [comment]
rebase-editor is made to be used on the command line.. Not sure I understand your workflow..

**Comment by Smolli** [comment]
I understand, that the editor is made for the command line. And that is where I use it. But using it also disables some advanced features of the IDE. My idea was, that there could be some compatibility mode where a third party application isn't blocked when using the editor.

**Comment by sjurba** [comment]
I see. So you want the IDE to not use the rebase-editor, which is not really something this app can control. But you can check the git preferences in you IDE and see if you can set the GIT_SEQUENCE_EDITOR environment variable. This will override your global config. Alternatively remove the rebase-editor from the global config and set this environment variable in your .bash_profile..

**Comment by Smolli** [comment]
Putting  the varaible into `.bash_profile` is the best solution! 

Thanks for the suggestion!
