### ISSUE TITLE
FR: Implement `break`, `label`, `reset` and `merge`.

### ISSUE THREAD

**Issue by real-yfprojects** [sjurba/rebase-editor#29]
These are all the commands available when rebasing (in German):

```
Befehle:
# p, pick <Commit> = Commit verwenden
# r, reword <Commit> = Commit verwenden, aber Commit-Beschreibung bearbeiten
# e, edit <Commit> = Commit verwenden, aber zum Nachbessern anhalten
# s, squash <Commit> = Commit verwenden, aber mit vorherigem Commit vereinen
# f, fixup <Commit> = wie "squash", aber diese Commit-Beschreibung verwerfen
# x, exec <Commit> = Befehl (Rest der Zeile) mittels Shell ausführen
# b, break = hier anhalten (Rebase später mit 'git rebase --continue' fortsetzen)
# d, drop <Commit> = Commit entfernen
# l, label <Label> = aktuellen HEAD mit Label versehen
# t, reset <Label> = HEAD zu einem Label umsetzen
# m, merge [-C <Commit> | -c <Commit>] <Label> [# <eineZeile>]
# .       Merge-Commit mit der originalen Merge-Commit-Beschreibung erstellen
# .       (oder die eine Zeile, wenn keine originale Merge-Commit-Beschreibung
# .       spezifiziert ist). Benutzen Sie -c <Commit> zum Bearbeiten der
# .       Commit-Beschreibung.
```

The `b`, `l`, `t` and `m` keys do not do anything.

### Tasks
- [x] break
- [x] label
- [x] reset
- [x] merge
- [ ] exec

**Comment by sjurba** [comment]
Hi, Per. Yes, lack of time. I use the tool my self and for what I need it just works. Since I developed it some new commands have been added to git and I have just not gotten around to adding them. I think some of the commands are trival to add, but some might be tricky.

Anyways, I'm more than open to PRs if anyone feels inclined to give it a crack!

**Comment by perlun** [comment]
Sounds good @sjurba. I gave this a brief look now, here's my draft (not yet fully complete): https://github.com/sjurba/rebase-editor/pull/30

**Comment by real-yfprojects** [comment]
A way to edit the rebase file in one's favourite editor and resume to *rebase-editor* afterwards won't be that comfortable but will still be better than not having the option to use these commands.

**Comment by sjurba** [comment]
Break is now supported. Adding the others will be a bigger undertaking.

**Comment by sjurba** [comment]
I also added support for update-ref, label, reset and merge now. You can not create them your self, so the keys for them don't work, but you should be able to move them around and delete them. Adding support for adding and editing those lines is a bigger undertaking, but with this at least it is possible to work with the --update-refs and --rebase-merges options, which I think is the most common use case. Closing this issue now, but feel free to open a new one if you have more feedback or request.
