### ISSUE TITLE
Support new --update-refs feature

### ISSUE THREAD

**Issue by JanTvrdik** [sjurba/rebase-editor#39]
Git added a new rebase feature: update-refs

https://github.blog/2022-10-03-highlights-from-git-2-38/#rebase-dependent-branches-with-update-refs

**Comment by mitchellbusby** [comment]
Hey @JanTvrdik what happens when you run with --update-refs right now? does it totally break or just doesn't give you control over what gets picked?

**Comment by JanTvrdik** [comment]
It's mostly unusable. You can only edit lines before the first update ref operation.

**Comment by sjurba** [comment]
I have added support for the --update-refs feature, in that you can move stuff around and drop the update-ref lines if you want. You can not add or edit those lines though, as that will be a bigger undertaking, but I think this should cover the most common use cases.
