### ISSUE TITLE
No scrolling for long commit lists

### ISSUE THREAD

**Issue by Turbo87** [sjurba/rebase-editor#6]
When I run a large rebase operation with a long list of commits I can't edit the commits at the bottom since the editor doesn't seem to support scrolling at the moment.

**Comment by sjurba** [comment]
Yes, this is true. Have run into this problem on occasion as well. It is on my list for improvements, but PR are always welcome aswell.

**Comment by sjurba** [comment]
Fixed in v2.0

**Comment by Turbo87** [comment]
awesome! 🎉

**Comment by sjurba** [comment]
Are you on Linux? Would you mind testing the new version a bit before I release it to npm?

**Comment by Turbo87** [comment]
Nope, OSX with iTerm2 and zsh

**Comment by sjurba** [comment]
Ok. But any feedback on that platform is also welcome. :)

mvh
Sjur Bakka
